# Generated by Django 5.1.4 on 2025-01-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.IntegerField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
