# Generated by Django 5.1.4 on 2025-01-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0003_remove_login_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Signup',
        ),
    ]
